# Server Profile - Headless server with hardware support
{ config, lib, pkgs, ... }:

{
  imports = [
    ../modules/security.nix
    ../modules/media-server.nix
  ];
  # Hardware support - generic UEFI system
  boot = {
    # Hardened kernel for security-focused server deployments
    kernelPackages = pkgs.linuxKernel.packages.linux_hardened;
    
    initrd = {
      availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
      kernelModules = [ ];
    };
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];
  };

  # Filesystem configuration is generated by nixos-generate-config
  # This ensures compatibility with both labels and UUIDs
  
  # No swap by default
  swapDevices = [ ];

  # Hardware settings
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # No desktop environment
  services.xserver.enable = false;
  
  # Server-optimized SSH with key-based authentication
  services.openssh = {
    enable = true;
    settings = {
      PasswordAuthentication = lib.mkForce false;
      PermitRootLogin = "no";
      X11Forwarding = false;
      MaxAuthTries = 3;
      ClientAliveInterval = 300;
      ClientAliveCountMax = 2;
    };
    openFirewall = true;
  };

  # Essential server packages
  environment.systemPackages = with pkgs; [
    # System monitoring
    htop
    iotop
    nethogs
    ncdu
    
    # Network tools
    nmap
    netcat
    tcpdump
    
    # Administration tools
    tmux
    screen
    
    # File management
    rsync
    rclone
  ];

  # Automatic updates for security (disabled by default to prevent issues)
  system.autoUpgrade = {
    enable = false; # Disabled to avoid absolute path issues
    allowReboot = false;
    # flake = "/etc/nixos"; # Absolute path not allowed in pure evaluation
    flags = [ "--update-input" "nixpkgs" "--commit-lock-file" ];
  };

  # Server services
  services = {
    # Log management
    journald.extraConfig = ''
      SystemMaxUse=1G
      MaxRetentionSec=7day
    '';
  };

  # Docker for containerized services
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
    autoPrune.dates = "weekly";
  };
  users.users.${config.myUser.username}.extraGroups = [ "docker" ];

  # Server performance optimizations
  boot.kernel.sysctl = {
    # Network optimizations
    "net.core.rmem_max" = 134217728;
    "net.core.wmem_max" = 134217728;
    "net.ipv4.tcp_rmem" = "4096 65536 134217728";
    "net.ipv4.tcp_wmem" = "4096 65536 134217728";
    
    # File system optimizations
    "fs.file-max" = 2097152;
    "fs.inotify.max_user_watches" = 524288;
  };

  # Enable optional modules (disabled by default)
  modules = {
    security.enable = true;
    media-server.enable = false;  # Enable manually if needed
  };
  
  # Production-ready firewall configuration
  networking.firewall = {
    enable = true;
    allowedTCPPorts = [ 22 ];  # SSH only by default
    allowedUDPPorts = [ ];
    allowPing = false;
    logReversePathDrops = true;
  };
}